version: 2.1

orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

jobs:
  build-python-ci-image:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD" 
      - run:
          name: Build python Docker image
          command: docker build -t kriordan/talk-booking:cicd-python3.9-slim ./ci_cd/python/
      - run:
          name: Push Docker image to Docker Hub
          command: docker push kriordan/talk-booking:cicd-python3.9-slim

  service-talk-booking-code-quality:
    working_directory: ~/talk-booking
    docker:
      - image: kriordan/talk-booking:cicd-python3.9-slim

    steps:
      - checkout
      - python/install-packages:
          app-dir: services/talk-booking/
          pkg-manager: poetry
      - run:
          name: Run code quality checks
          working_directory: services/talk-booking/
          command: |
            poetry run flake8
            poetry run black . --check
            poetry run isort . --check-only --profile black
            poetry run bandit .
            poetry run safety check

workflows:
  talk-booking: 
    jobs:
      - build-python-ci-image
      - service-talk-booking-code-quality
